example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from unicodedata import name
from django.urls import path
from wishlist.views import get_wishlist_ajax, show_wishlist, show_wishlist_xml, show_wishlist_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, wishlist_ajax, add_wishlist, get_wishlist_ajax

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_wishlist_xml, name='show_wishlist_xml'),
    path('json/', show_wishlist_json, name='show_wishlist_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', wishlist_ajax, name='wishlist_ajax'),
    path('add_wishlist/', add_wishlist, name='add_wishlist'),
    path('get_wishlist_ajax', get_wishlist_ajax, name='get_wishlist_ajax')
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

    def __str__(self):
        return self.nama_barang

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from curses.ascii import HT
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Hadziq',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def wishlist_ajax(request):
    context = {
        'nama': 'Hadziq',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)
    # data_barang_wishlist = BarangWishlist.objects.all()
    # context = {
    #     'list_barang': data_barang_wishlist,
    #     'nama': 'Hadziq',
    #     'last_login': request.COOKIES['last_login'],
    # }


@login_required(login_url='/wishlist/login/')
def get_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize('json', data_barang_wishlist))

@login_required(login_url="/wishlist/login/")
def add_wishlist(request):
    if request.method == 'POST':
        nama_barang = request.POST.get('nama_barang')
        harga = request.POST.get('harga')
        deskripsi = request.POST.get('deskripsi')
        new_barang = BarangWishlist(
            nama_barang = nama_barang,
            harga_barang = harga,
            deskripsi = deskripsi,
        )
        new_barang.save()
        return HttpResponse(b"Created", status=201)
    return HttpResponseNotFound()
    # if request.method == "POST":
    #     nama_barang = request.POST.get('nama_barang')
    #     harga = request.POST.get('harga')
    #     deskripsi = request.POST.get('deskripsi')
    #     new_barang = BarangWishlist(
    #         nama_barang = nama_barang,
    #         harga_barang = harga,
    #         deskripsi = deskripsi,
    #     )
    #     new_barang.save()
    #     data_barang_wishlist = BarangWishlist.objects.all()
    # return HttpResponse(b"Created", status=201)
    # return redirect('wishlist:wishlist_ajax')


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response
    
def show_wishlist_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_wishlist_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class="mx-auto" style="width: 1000px; padding: 100px;">
    <form method="POST" action="">
        {% csrf_token %}

        <!-- Email input -->
        <div class="form-outline mb-4">
        <input type="text" id="form2Example1" class="form-control" name="username" placeholder="Username"/>
        <label class="form-label" for="form2Example1">Username</label>
        </div>
    
        <!-- Password input -->
        <div class="form-outline mb-4">
        <input type="password" id="form2Example2" class="form-control" name="password" placeholder="Password"/>
        <label class="form-label" for="form2Example2">Password</label>
        </div>
    
        <!-- Submit button -->
        <!-- <button type="button" class="btn btn-primary btn-block mb-4">Sign in</button> -->
        <input class="btn btn-primary btn-block mb-4" type="submit" value="Login">
    
        <!-- Register buttons -->
        <div class="text-center">
        <p>Not a member? <a href="{% url 'wishlist:register' %}">Register</a></p>

        </div>
    </form>
</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#">{{nama}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'wishlist:logout' %}">Logout</a>
        </li>
      
    </div>
  </nav>
<br>
<br>
<br>

<table class="table table-dark table-striped table-hover mx-auto" style="width: 1100px; padding: 50px;">
    <thead>
        <tr>
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
        </tr>
    </thead>
    <tbody>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
        {% endfor %}
    </tbody>
</table>
<h5 class="mx-auto" style="width: 1000px; padding: 100px;">Sesi terakhir login: {{ last_login }}</h5>


{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#">{{nama}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'wishlist:logout' %}">Logout</a>
        </li>
      
    </div>
  </nav>
<br>
<br>
<br>


<body>
<table id="mylist" class="table table-striped table-hover mx-auto" style="width: 1100px; padding: 50px;">
    <!-- <thead>
        <tr>
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
        </tr>
    </thead> -->
    <!-- <tbody>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
        {% endfor %}
    </tbody> -->
</table>
<div class="container-fluid">
  <form id="form_add" method="POST" action="{% url 'wishlist:add_wishlist' %}">
    {% csrf_token %}
    <label class="nama" for="nama">Nama barang</label>
    <input type="text" id="nama" class="form-control" name="nama_barang"/>

    <label class="harga" for="harga">Harga</label>
    <input type="text" id="harga" class="form-control" name="harga"/>

    <label class="deskripsi" for="deskripsi">Deskripsi</label>
    <input type="text" id="deskripsi" class="form-control" name="deskripsi"/>

    <button type="submit" id="btn-submit">Tambahkan</button>
  </form>
</div>
<!-- <script>
  $('#btn-submit').click(function(){
    var nama = $('#nama').val();
    var harga = $('#harga').val();
    var deskripsi = $('#deskripsi').val();

    $.post("",{
      nama:nama,
      harga:harga,
      deskripsi:deskripsi,
    }), function(response){
      
    }

  })
</script> -->

<h5 class="mx-auto" style="width: 1000px; padding: 100px;">Sesi terakhir login: {{ last_login }}</h5>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-- <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script> -->
<script>

    async function getDataBarang() {
        return fetch("{% url 'wishlist:get_wishlist_ajax' %}").then((res) => res.json())
    }

    async function refreshWishlist() {
        document.getElementById("mylist").innerHTML = ""
        const wishlist = await getDataBarang()
        let table = `<tr>
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
        </tr>`
        wishlist.forEach((item) => {
            table += `\n<tr>
                <td>${item.fields.nama_barang}</td>
                <td>${item.fields.harga_barang}</td>
                <td>${item.fields.deskripsi}</td>
            </tr>`
        });
        document.getElementById("mylist").innerHTML = table
    }

    function addWishlsit() {
        fetch("{% url 'wishlist:add_wishlist' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form_add'))
        }).then(refreshWishlist)
        return false
    }

    document.getElementById('btn-submit').onclick = addWishlsit
    refreshWishlist()
    // $(document).ready(function() {
    //     get_data_barang();
    //     function get_data_barang() {
    //         $.get("../json", function(data) {
    //             data.forEach(element => {
    //                 var tr = $("<tr></tr>");
    //                 for (const [key, value] of Object.entries(element.fields)) {
    //                     var td = $("<td></td>").html(value);
    //                     tr.append(td);
    //                 }
    //                 $("#mylist").append(tr);
    //             });
    //         });
    //     }

    //     $("#btn-submit").submit(function(event) {

    //         event.preventDefault();
    //         var url = event.currentTarget.action;
        
    //         $.ajax({
    //             url: "{% url 'wishlist:add_wishlist' %}",
    //             type: post,
    //             dataType: 'json',
    //             success: function(data) {

    //                 for (i=0; i<data.length; i++) {
    //                     $("#mylist").append("<tr>"+data[i].fields.nama_barang+"</tr>")
    //                 }
    //                 get_data_barang();


    //             }
    //         });
    //         // $.ajax({
    //         //     url: "{% url 'wishlist:add_wishlist' %}",
    //         //     type: post,
    //         //     dataType: 'json',
    //         //     success: function(data) {
    //         //         var tr = $("<tr></tr>");
    //         //         for (const [key, value] of Object.entries(data)) {
    //         //             var td = $("<td></td>").html(value);
    //         //             tr.append(td);
    //         //         }
    //         //         $("#mylist").append(tr);

    //         //     }
    //         // });
    //     });
    // });

  // $.ajax({
  //   type: 'GET',
  //   url: 'http://127.0.0.1:8000/wishlist/json/',
  //   dataType: 'json',
  //   success: function(data) {
  //     var data1 = JSON.stringify(data);
  //     var lists = JSON.parse(data1);
  //     // console.log(lists[0].fields['nama_barang'])
  //     for (var i = 0; i < data.length; i++) {
  //       var baris = $('<tr><td>' + lists[i].fields['nama_barang'] + '</td><td>' + lists[i].fields['harga_barang'] + '</td><td>' + lists[i].fields['deskripsi'] + '</td></tr>');
  //       $('#mylist').append(baris);
  //     }
  //   },
  // });

</script>
{% endblock content %}